### ISSUE TITLE
IE에서 bindEvents 이벤트 에러

### ISSUE THREAD

**Issue by yousung** [okchangwon/vue-daum-map#1]
IE에서 초기 맵 로드시 bindEvents 이벤트

151번 

 for (let event of EVENTS) {
          this.bindEvent(event, handlers[event]);
} 

부분이 에러를 발생합니다.
저는 of 대신 in 으로 바꿔서 사용하였습니다.

**Comment by okchangwon** [comment]
ES6 기반 코드에서 배열을 순회할 때 for of를 사용합니다.
어떤 이유로 트랜스파일링이 제대로 수행되지 않아서 for of가 코드상에 그대로 남아
IE에서 오류를 일으킨게 아닌가 싶네용
