### ISSUE TITLE
nuxt 호환성

### ISSUE THREAD

**Issue by seongjoojin** [okchangwon/vue-daum-map#2]
nuxt에서는 호환되지 않는건가요?
계속 삽질해보는데 전혀 동작하지 않네요..

**Comment by okchangwon** [comment]
nuxt.js, next.js 등은 전혀 고려하지 않았습니다.
애초에 daum map 자체가 서버사이드 렌더링에 대한 지원이나 예외처리를 하지 않고 있을 것 같아요.

**Comment by seongjoojin** [comment]
넵 알겠습니다.
