### ISSUE TITLE
Marker를 표시 하고 싶습니다.

### ISSUE THREAD

**Issue by hanjool** [okchangwon/vue-daum-map#3]
방법을 모르겠네요 ..

답변에 미리 감사 드립니다.

**Comment by hanjool** [comment]
이유가 있나요?

**Comment by ijy5154** [comment]
해당 내용으로 확인중에 해결하여 이와같은 문제 있으신 분들이 있을거 같아 링크 남깁니다. 

https://devtalk.kakao.com/t/vue-js/53927/2

**Comment by okchangwon** [comment]
답변이 너무 늦어서 죄송합니다.
컴포넌트로 부터 map 객체를 전달받고([참고](https://github.com/okchangwon/vue-daum-map#%EB%A9%94%EC%84%9C%EB%93%9C-%EC%98%88%EC%A0%9C
))
[마커 생성 가이드](http://apis.map.kakao.com/web/documentation/#Marker)대로 작업하시면 될 것 같습니다.

**Comment by GauthierPLM** [comment]
@okchangwon could you give a short code example of how we are supposed to add a marker to the map?

I succeeded to access Kakao' API but I have the error `Vue warn]: Error in callback for watcher "map": "TypeError: this.P is not a function"` with the following code:

```JS
  data: () => ({
    map: null
  }),
  methods: {
    mapLoaded(map) {
      this.map = map;

      window.kakao.maps.Marker({
        map: this.map,
        position: window.kakao.maps.LatLng(37.486979, 127.104046)
      });
    }
  }
```

I am not really fluent in Korean (but have to work with Kakao Map) so I might have missed something.
